// Short editorial paraphrases, not copied articles. Scope: general principles;
// International and Punjab sources have explicit scopes; no treatment rates are inferred.
export const knowledge = [
  { id: 'WHEAT-01', topic: 'Crop health', title: 'Recognizing wheat leaf rust', publisher: 'University of Nebraska–Lincoln Extension', url: 'https://extensionpubs.unl.edu/publication/g2180/2012/pdf/view/g2180-2012.pdf', scope: 'Wheat symptom recognition; Nebraska, USA', text: 'Wheat leaf rust produces small orange-brown pustules, commonly on the upper leaf surface. Their arrangement is scattered rather than organized into stripes. Compare pustule color, shape and distribution when distinguishing wheat rust diseases.' },
  { id: 'WHEAT-02', topic: 'Crop health', title: 'Distinguishing stripe rust', publisher: 'University of Nebraska–Lincoln Extension', url: 'https://extensionpubs.unl.edu/publication/g2180/2012/pdf/view/g2180-2012.pdf', scope: 'Wheat symptom recognition; Nebraska, USA', text: 'Stripe rust typically shows orange-yellow pustules arranged in stripes on wheat leaves. Leaf rust and stem rust differ in pustule appearance and location. Rust management depends on disease identification and field conditions.' },
  { id: 'SOIL-01', topic: 'Soil interpretation', title: 'Read values in their laboratory context', publisher: 'University of Minnesota Extension', url: 'https://extension.umn.edu/agriculture/crop-production/nutrient-management-for-minnesota-crops/understanding-the-soil-test-report', scope: 'General soil-test principles; Minnesota, USA', text: 'Soil test numbers come from analytical measurements. Laboratory results are interpreted to estimate nutrient availability and the likelihood of a crop response to added nutrients. Use the report interpretation with the measurement instead of treating an isolated number as a fertilizer recommendation.' },
  { id: 'SOIL-02', topic: 'Soil interpretation', title: 'pH and nutrient availability', publisher: 'University of Maryland Extension', url: 'https://www.extension.umd.edu/resource/understanding-your-soil-test-report', scope: 'General soil chemistry; source discusses gardens and lawns', text: 'Soil pH influences nutrient availability, and plants differ in their preferred pH range. Measured pH and buffer pH have different roles: buffer pH helps determine lime requirements. A pH reading alone is insufficient to calculate a lime application.' },
  { id: 'WATER-01', topic: 'Water management', title: 'Account for water entering and leaving the soil', publisher: 'University of Minnesota Extension', url: 'https://extension.umn.edu/natural-resources/conservation/agricultural-soil-and-water/irrigation/irrigation-scheduling-checkbook-method', scope: 'General irrigation scheduling; Minnesota, USA', text: 'Irrigation scheduling can track soil water through a daily checkbook: rainfall and irrigation add water, while crop water use removes it. Soil moisture observations and information about the soil and crop help determine when irrigation is needed.' }
, {"id":"FIELD-01","topic":"Field checks","title":"Verify symptoms in field context","publisher":"FAO","url":"https://www.fao.org/4/x8234e/x8234e08.htm","scope":"General wheat field diagnosis; not a local prescription","text":"Wheat problems have several possible environmental and nutritional causes. Check field patterns and growing conditions before selecting an intervention."},
{"id":"FAO-01","topic":"Nutrition","title":"Match nutrients to local conditions","publisher":"FAO","url":"https://www.fao.org/4/x8234e/x8234e08.htm","scope":"General wheat nutrition; local calibration required","text":"Nutrient recommendations vary with soil fertility and crop requirements. A universal fertilizer rate does not fit every field."},
{"id":"FAO-02","topic":"Soil interpretation","title":"Check pH through the root zone","publisher":"FAO","url":"https://www.fao.org/4/x8234e/x8234e08.htm","scope":"General wheat soil assessment","text":"Soil pH affects nutrient availability. Sampling at different rooting depths can help investigate acidity or alkalinity."},
{"id":"FAO-03","topic":"Water management","title":"Heat and water stress interact","publisher":"FAO","url":"https://www.fao.org/4/x8234e/x8234e08.htm","scope":"General wheat physiology; no irrigation schedule","text":"Heat damage can coincide with water stress. Consider moisture conditions when investigating heat-related crop damage."},
{"id":"DRY-01","topic":"Nutrition","title":"Test soil and tissue where appropriate","publisher":"FAO","url":"https://www.fao.org/4/Y4011E/y4011e0s.htm","scope":"Dryland wheat; international guidance","text":"Crop nutrition should consider nutrient supply, losses and demand, with soil and tissue testing where appropriate."},
{"id":"DRY-02","topic":"Field management","title":"Assess management factors together","publisher":"FAO","url":"https://www.fao.org/4/Y4011E/y4011e0s.htm","scope":"Dryland wheat; international guidance","text":"Weed control, sowing time and crop nutrition can constrain water-use efficiency. Review management history alongside soil and weather evidence."},
{"id":"DATA-01","topic":"Soil methods","title":"Keep soil analytical methods attached","publisher":"ISRIC","url":"https://docs.isric.org/globaldata/wosis/faq-wosis.html","scope":"Global soil data comparability; not treatment guidance","text":"Soil properties are grouped by operationally comparable analytical procedures. Results from different methods are not automatically interchangeable."},
{"id":"DATA-02","topic":"Soil methods","title":"Preserve sampling context","publisher":"ISRIC","url":"https://docs.isric.org/globaldata/wosis/faq-wosis.html","scope":"Global soil profile data; not field-specific measurements","text":"Soil surveys differ in depth and measured properties. Retain profile, layer and measurement context when comparing records."},
{"id":"PK-01","topic":"Local services","title":"Use local soil and water advisory testing","publisher":"Punjab Agriculture Department","url":"https://agripunjab.gov.pk/ssri-achievements","scope":"Punjab, Pakistan; service and research context","text":"Punjab soil salinity research includes soil and water advisory testing. Local testing is relevant when investigating salinity and irrigation-water problems."}
];
const tokenize = (s) => s.toLowerCase().match(/[a-z0-9]+/g) || [];
const stop = new Set(['the', 'and', 'a', 'of', 'to', 'in', 'is', 'for', 'on', 'with', 'or', 'from', 'an', 'as']);
export function retrieve(query, limit = 4) {
  const terms = new Set(tokenize(query).filter(x => !stop.has(x)));
  if (!terms.size) return [];
  const docs = knowledge.map(d => tokenize(`${d.title} ${d.text}`));
  return knowledge.map((doc, i) => {
    let score = 0;
    for (const t of terms) {
      const count = docs[i].filter(v => v === t).length;
      const df = docs.filter(tokens => tokens.includes(t)).length;
      if (count) score += (1 + Math.log(count)) * Math.log(1 + docs.length / (1 + df));
    }
    return { ...doc, score: Number((score / Math.sqrt(docs[i].length)).toFixed(4)) };
  }).filter(d => d.score > 0).sort((a, b) => b.score - a.score).slice(0, limit);
}
